// AZIMUTH — baked-in demo data (static, frontend-only build).
// Photography: Unsplash (free under the Unsplash License). One verified
// photo per car, matched to its actual make/model.
import type { Vehicle } from "./types";

const u = (id: string, w = 1800) =>
  `https://images.unsplash.com/photo-${id}?q=80&w=${w}&auto=format&fit=crop`;

const IMG = {
  porsche911: "1550855909-c4f6798dd77f",
  taycan: "1634317558729-c410a4133faa",
  aston: "1565793463692-83267d9ee3bf",
  bentley: "1678026545752-bfda7ec6d747",
  mercedesS: "1750800669854-0a6f5df93906",
  mercedesSL: "1719811313314-310ebd8a4339",
  ferrariRoma: "1606220838315-056192d5e927",
  ferrari488: "1601937222273-e318eb01b3ca",
  lambo: "1740806826463-eaed9946bed3",
  bmwM4: "1752774224823-c86876576dfb",
  audi: "1654855384677-6880377e4ed5",
  maserati: "1561444490-48fbdf5d9683",
};

type RawVehicle = Omit<Vehicle, "id" | "createdAt" | "available" | "isFavorite">;

const RAW: RawVehicle[] = [
  {
    slug: "porsche-911-carrera-gts",
    make: "Porsche",
    model: "911 Carrera GTS",
    year: 2024,
    category: "SPORT",
    tagline: "The benchmark, sharpened.",
    description:
      "Half a century of refinement distilled into a shape you would recognise blindfolded. The Carrera GTS sits in the sweet spot of the range — quick enough to thrill, composed enough to live with. Reach for it when the road matters more than the destination.",
    dailyRate: 560,
    seats: 4,
    doors: 2,
    transmission: "DUAL_CLUTCH",
    drivetrain: "RWD",
    fuelType: "PETROL",
    powerHp: 473,
    zeroToSixty: 3.3,
    topSpeed: 193,
    rangeOrTank: "16.9 gal",
    engine: "3.0L twin-turbo flat-six",
    color: "Agate Grey",
    features: [
      "Sport Chrono package",
      "Adaptive sport seats",
      "Bose surround sound",
      "Rear-axle steering",
      "Sport exhaust",
      "Apple CarPlay",
    ],
    images: [u(IMG.porsche911)],
    location: "Los Angeles",
    lat: 34.0522,
    lng: -118.2437,
    featured: true,
  },
  {
    slug: "porsche-taycan-turbo-s",
    make: "Porsche",
    model: "Taycan Turbo S",
    year: 2024,
    category: "ELECTRIC",
    tagline: "Silence, then physics.",
    description:
      "There is no warning. One moment you are still, the next the horizon is closer. The Taycan Turbo S delivers its performance without theatre — no engine note, no drama, only a quiet, relentless surge that rearranges your sense of speed.",
    dailyRate: 640,
    seats: 4,
    doors: 4,
    transmission: "SINGLE_SPEED",
    drivetrain: "AWD",
    fuelType: "ELECTRIC",
    powerHp: 750,
    zeroToSixty: 2.6,
    topSpeed: 162,
    rangeOrTank: "242 mi range",
    engine: "Dual permanent-magnet motors",
    color: "Frozen Blue Metallic",
    features: [
      "800V fast charging",
      "Adaptive air suspension",
      "Panoramic glass roof",
      "Performance Battery Plus",
      "Lane keep assist",
      "Ambient lighting",
    ],
    images: [u(IMG.taycan)],
    location: "San Francisco",
    lat: 37.7749,
    lng: -122.4194,
    featured: false,
  },
  {
    slug: "aston-martin-db12",
    make: "Aston Martin",
    model: "DB12",
    year: 2024,
    category: "GRAND_TOURER",
    tagline: "A grand tourer with teeth.",
    description:
      "Aston calls it a super tourer, and for once the marketing is honest. The DB12 covers continents in tailored leather while keeping a V8 snarl within reach. It is the car you take when the drive is the holiday.",
    dailyRate: 980,
    seats: 2,
    doors: 2,
    transmission: "AUTOMATIC",
    drivetrain: "RWD",
    fuelType: "PETROL",
    powerHp: 671,
    zeroToSixty: 3.5,
    topSpeed: 202,
    rangeOrTank: "19.3 gal",
    engine: "4.0L twin-turbo V8",
    color: "Iridescent Emerald",
    features: [
      "Bowers & Wilkins audio",
      "Carbon-ceramic brakes",
      "Hand-stitched leather cabin",
      "Adaptive dampers",
      "360° camera",
      "Heated & cooled seats",
    ],
    images: [u(IMG.aston)],
    location: "Monterey",
    lat: 36.6002,
    lng: -121.8947,
    featured: true,
  },
  {
    slug: "bentley-continental-gt",
    make: "Bentley",
    model: "Continental GT Speed",
    year: 2023,
    category: "GRAND_TOURER",
    tagline: "Effortless, by the tonne.",
    description:
      "A W12 that moves two and a half tonnes like a thought, wrapped in enough wood and hide to furnish a study. The Continental GT does not chase corners so much as dismiss them. First class, with a steering wheel.",
    dailyRate: 1150,
    seats: 4,
    doors: 2,
    transmission: "DUAL_CLUTCH",
    drivetrain: "AWD",
    fuelType: "PETROL",
    powerHp: 650,
    zeroToSixty: 3.5,
    topSpeed: 208,
    rangeOrTank: "23.8 gal",
    engine: "6.0L twin-turbo W12",
    color: "Glacier White",
    features: [
      "Rotating dashboard display",
      "Naim for Bentley audio",
      "Diamond-quilted leather",
      "Active all-wheel drive",
      "Night vision",
      "Massage seats",
    ],
    images: [u(IMG.bentley)],
    location: "Beverly Hills",
    lat: 34.0736,
    lng: -118.4004,
    featured: false,
  },
  {
    slug: "mercedes-benz-s580",
    make: "Mercedes-Benz",
    model: "S 580 4MATIC",
    year: 2024,
    category: "SALOON",
    tagline: "The office that drives you.",
    description:
      "The S-Class has spent forty years deciding what luxury means, then quietly shipping it to everyone else a decade later. Rear-seat executive package, near-silent cabin, a ride that irons the city flat. Arrive composed.",
    dailyRate: 520,
    seats: 5,
    doors: 4,
    transmission: "AUTOMATIC",
    drivetrain: "AWD",
    fuelType: "HYBRID",
    powerHp: 496,
    zeroToSixty: 4.4,
    topSpeed: 130,
    rangeOrTank: "21.1 gal",
    engine: "4.0L V8 + EQ Boost",
    color: "Obsidian Black",
    features: [
      "Rear executive seats",
      "Burmester 4D sound",
      "MBUX augmented navigation",
      "Active ambient lighting",
      "Rear-seat tablet",
      "Chauffeur package",
    ],
    images: [u(IMG.mercedesS)],
    location: "New York",
    lat: 40.7128,
    lng: -74.006,
    featured: true,
  },
  {
    slug: "mercedes-amg-sl63",
    make: "Mercedes-AMG",
    model: "SL 63 Roadster",
    year: 2024,
    category: "ROADSTER",
    tagline: "Roof down, decade back.",
    description:
      "The SL returned to its roots — a proper folding-roof grand tourer with AMG muscle underneath. Drop the fabric top, point it at the coast, and let the V8 do the talking. Built for golden hour and the long way home.",
    dailyRate: 720,
    seats: 4,
    doors: 2,
    transmission: "AUTOMATIC",
    drivetrain: "AWD",
    fuelType: "PETROL",
    powerHp: 577,
    zeroToSixty: 3.5,
    topSpeed: 196,
    rangeOrTank: "18.0 gal",
    engine: "4.0L twin-turbo V8",
    color: "Patagonia Red",
    features: [
      "Fabric soft top",
      "AMG Ride Control",
      "Airscarf neck-level heating",
      "Burmester surround sound",
      "Rear-axle steering",
      "Heated steering wheel",
    ],
    images: [u(IMG.mercedesSL)],
    location: "Miami",
    lat: 25.7617,
    lng: -80.1918,
    featured: false,
  },
  {
    slug: "ferrari-roma",
    make: "Ferrari",
    model: "Roma",
    year: 2023,
    category: "GRAND_TOURER",
    tagline: "La dolce vita, certified.",
    description:
      "Ferrari's most understated proposition — clean lines, a front-mid V8, and a cabin that whispers rather than shouts. The Roma is a Ferrari for people who already know they own one. Effortless on a boulevard, electric on a mountain pass.",
    dailyRate: 1290,
    seats: 2,
    doors: 2,
    transmission: "DUAL_CLUTCH",
    drivetrain: "RWD",
    fuelType: "PETROL",
    powerHp: 612,
    zeroToSixty: 3.4,
    topSpeed: 199,
    rangeOrTank: "21.1 gal",
    engine: "3.9L twin-turbo V8",
    color: "Rosso Corsa",
    features: [
      "Manettino dynamic modes",
      "Carbon-fibre interior trim",
      "16-inch digital cluster",
      "Magnetorheological dampers",
      "Front-lift system",
      "JBL Professional audio",
    ],
    images: [u(IMG.ferrariRoma)],
    location: "Miami",
    lat: 25.7617,
    lng: -80.1918,
    featured: true,
  },
  {
    slug: "ferrari-488-pista",
    make: "Ferrari",
    model: "488 Pista",
    year: 2020,
    category: "SPORT",
    tagline: "Track distilled, road legal.",
    description:
      "Born from Ferrari's racing programme and barely softened for the street. The Pista is loud, focused, and uncompromising — a car that rewards commitment and punishes hesitation. Reserve it for a closed road and an early start.",
    dailyRate: 1650,
    seats: 2,
    doors: 2,
    transmission: "DUAL_CLUTCH",
    drivetrain: "RWD",
    fuelType: "PETROL",
    powerHp: 710,
    zeroToSixty: 2.8,
    topSpeed: 211,
    rangeOrTank: "20.6 gal",
    engine: "3.9L twin-turbo V8",
    color: "Giallo Modena",
    features: [
      "Carbon-fibre bonnet & wheels",
      "Ferrari Dynamic Enhancer",
      "Race-spec bucket seats",
      "Titanium exhaust",
      "Telemetry data logging",
      "Carbon-ceramic brakes",
    ],
    images: [u(IMG.ferrari488)],
    location: "Las Vegas",
    lat: 36.1699,
    lng: -115.1398,
    featured: false,
  },
  {
    slug: "lamborghini-huracan-evo",
    make: "Lamborghini",
    model: "Huracán EVO",
    year: 2022,
    category: "SPORT",
    tagline: "A V10 with no apology.",
    description:
      "The last of the naturally aspirated greats. No turbos, no hybrid assistance — just ten cylinders spinning to 8,500 rpm and a noise that sets off car alarms two streets over. Subtlety is not on the options list.",
    dailyRate: 1480,
    seats: 2,
    doors: 2,
    transmission: "DUAL_CLUTCH",
    drivetrain: "AWD",
    fuelType: "PETROL",
    powerHp: 631,
    zeroToSixty: 2.9,
    topSpeed: 202,
    rangeOrTank: "21.1 gal",
    engine: "5.2L naturally-aspirated V10",
    color: "Arancio Borealis",
    features: [
      "Lamborghini Dinamica Veicolo",
      "Magneto-rheological suspension",
      "Anima drive selector",
      "Carbon-ceramic brakes",
      "Lifting system",
      "Sensonum audio",
    ],
    images: [u(IMG.lambo)],
    location: "Las Vegas",
    lat: 36.1699,
    lng: -115.1398,
    featured: false,
  },
  {
    slug: "bmw-m4-competition",
    make: "BMW",
    model: "M4 Competition",
    year: 2024,
    category: "SPORT",
    tagline: "The everyday weapon.",
    description:
      "Brutal when you ask, civil when you don't. The M4 Competition carries decades of M-division knowledge in a body you can park at the grocery store. A proper analogue thrill with a digital safety net.",
    dailyRate: 440,
    seats: 4,
    doors: 2,
    transmission: "AUTOMATIC",
    drivetrain: "AWD",
    fuelType: "PETROL",
    powerHp: 503,
    zeroToSixty: 3.4,
    topSpeed: 180,
    rangeOrTank: "15.6 gal",
    engine: "3.0L twin-turbo inline-six",
    color: "São Paulo Yellow",
    features: [
      "M xDrive with 2WD mode",
      "Adaptive M suspension",
      "Carbon bucket seats",
      "Harman Kardon audio",
      "M Drive Professional",
      "Laser headlights",
    ],
    images: [u(IMG.bmwM4)],
    location: "Austin",
    lat: 30.2672,
    lng: -97.7431,
    featured: false,
  },
  {
    slug: "audi-rs-etron-gt",
    make: "Audi",
    model: "RS e-tron GT",
    year: 2024,
    category: "ELECTRIC",
    tagline: "The quiet revolution.",
    description:
      "Proof that an electric car can have a soul. The RS e-tron GT pairs ballistic acceleration with the kind of design restraint that ages well. Charge it overnight, and drive a week of commutes that feel like an event.",
    dailyRate: 560,
    seats: 4,
    doors: 4,
    transmission: "SINGLE_SPEED",
    drivetrain: "AWD",
    fuelType: "ELECTRIC",
    powerHp: 637,
    zeroToSixty: 3.1,
    topSpeed: 155,
    rangeOrTank: "232 mi range",
    engine: "Dual electric motors",
    color: "Tactical Green",
    features: [
      "270kW DC fast charging",
      "Adaptive air suspension",
      "Matrix LED headlights",
      "Carbon roof",
      "Bang & Olufsen 3D audio",
      "Virtual cockpit plus",
    ],
    images: [u(IMG.audi)],
    location: "Seattle",
    lat: 47.6062,
    lng: -122.3321,
    featured: false,
  },
  {
    slug: "maserati-granturismo",
    make: "Maserati",
    model: "GranTurismo Trofeo",
    year: 2024,
    category: "GRAND_TOURER",
    tagline: "Italy's long-distance argument.",
    description:
      "A genuine four-seat grand tourer with a Nettuno V6 and a soundtrack to match. The GranTurismo is rarer than the German alternatives and all the more compelling for it — beautiful in a way that photographs never quite capture.",
    dailyRate: 610,
    seats: 4,
    doors: 2,
    transmission: "AUTOMATIC",
    drivetrain: "AWD",
    fuelType: "PETROL",
    powerHp: 542,
    zeroToSixty: 3.5,
    topSpeed: 199,
    rangeOrTank: "19.8 gal",
    engine: "3.0L twin-turbo V6 (Nettuno)",
    color: "Grigio Lava",
    features: [
      "Sonus faber audio",
      "Air suspension",
      "Full-grain leather",
      "12.3-inch central display",
      "Launch control",
      "Adaptive cruise",
    ],
    images: [u(IMG.maserati)],
    location: "Aspen",
    lat: 39.1911,
    lng: -106.8175,
    featured: false,
  },
];

// Stable ids (= slug) and ascending createdAt so the default sort
// (featured first, then oldest-added) is deterministic.
export const seedVehicles: Vehicle[] = RAW.map((v, i) => ({
  ...v,
  id: v.slug,
  available: true,
  createdAt: new Date(Date.UTC(2025, 0, 1) + i * 86_400_000).toISOString(),
}));

export interface SeedUser {
  id: string;
  email: string;
  name: string;
  role: "USER" | "ADMIN";
  phone: string | null;
  city: string | null;
  avatarUrl: string | null;
  createdAt: string;
  password: string;
}

export const seedUsers: SeedUser[] = [
  {
    id: "u_admin",
    email: "admin@azimuth.travel",
    name: "Avery Sloane",
    role: "ADMIN",
    phone: "+1 310 555 0142",
    city: "Los Angeles",
    avatarUrl: null,
    createdAt: new Date(Date.UTC(2024, 10, 2)).toISOString(),
    password: "azimuth-admin",
  },
  {
    id: "u_member",
    email: "member@azimuth.travel",
    name: "Jordan Hale",
    role: "USER",
    phone: null,
    city: "Miami",
    avatarUrl: null,
    createdAt: new Date(Date.UTC(2025, 0, 18)).toISOString(),
    password: "azimuth-member",
  },
];

// Member's saved cars: Ferrari Roma + Porsche Taycan.
export const seedFavorites: { userId: string; vehicleId: string }[] = [
  { userId: "u_member", vehicleId: "ferrari-roma" },
  { userId: "u_member", vehicleId: "porsche-taycan-turbo-s" },
];
